[ERROR] - 04/10/2021 14:11:37 - <class 'pyodbc.ProgrammingError'>
